version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      TERM: dumb
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.gradle.kts" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
    - run: gradle dependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle.kts" }}
    - run: ./gradlew check
  release:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: ./gradlew final publishPlugins -Prelease.useLastTag=true
workflows:
  version: 2
  build:
    jobs:
      - build
  release:
    jobs:
      - release
          filters:
            tags:
              only: /^v\.\d+\.\d+\.\d+$/

