defaults: &defaults
  docker:
  - image: circleci/openjdk:8-jdk
  working_directory: ~/repo
  environment:
    TERM: dumb

version: 2
jobs:
  cache_dependencies:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.gradle.kts" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
    - run: ./gradlew dependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle.kts" }}
  build:
    <<: *defaults
    steps:
    - checkout
    - run: ./gradlew check
  release:
    <<: *defaults
    steps:
    - checkout
    - run: ./gradlew final publishPlugins -Prelease.useLastTag=true
workflows:
  version: 2
  build:
    jobs:
    - cache_dependencies
    - build:
        requires:
          - cache_dependencies
  release-from-tag:
    jobs:
    - cache_dependencies
    - release:
        requires:
        - cache_dependencies
        filters:
          tags:
            only: /^v\.\d+\.\d+\.\d+$/
          branches:
            ignore: /.*/
